server:
  AppVersion: 0.1.0
  Port: :5000
  PprofPort: :5555
  Mode: Development
  JwtSecretKey: somesecretkey
  CookieName: jwt-token
  ReadTimeout: 10
  WriteTimeout: 10
  SSL: false
  CtxDefaultTimeout: 12
  CSRF: false
  Debug: true
  ApiKey: secretapikey

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: console
  Level: info

redis:
  RedisAddr: addr:port
  RedisPassword: pass
  RedisUsername: default
  RedisDb: 0
  RedisDefaultdb: 0
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Password: ""
  DB: 0

metrics:
  URL: localhost:7070
  ServiceName: gojira

github:
  token: your_github_token
  version: "2022-11-28"
  owner: your_github_owner_title

discord:
  ApiKey: your_discord_api_key

slack:
  ApiKey: your_slack_api_key