server:
  AppVersion: 0.1.0
  Port: :5000
  PprofPort: :5555
  Mode: Development
  JwtSecretKey: somesecretkey
  CookieName: jwt-token
  ReadTimeout: 10
  WriteTimeout: 10
  SSL: false
  CtxDefaultTimeout: 12
  CSRF: false
  Debug: true
  ApiKey: secretapikey

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: console
  Level: info

redis:
  RedisAddr: addr:port
  RedisPassword: pass
  RedisUsername: default
  RedisDb: 0
  RedisDefaultdb: 0
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Password: ""
  DB: 0

metrics:
  URL: localhost:7070
  ServiceName: gojira

jira:
  BaseUrl: "https://yourcompany.atlassian.net/browse/"
  
github:
  Token: your_github_token
  Version: "2022-11-28"
  Owner: your_github_owner_title
  Enable: false

discord:
  BotToken: your_discord_api_key
  Enable: true
  GuildID: "your guild id"

slack:
  ApiKey: your_slack_api_key
  Enable: false

chatgpt:
  token: sk-something